### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by 2black0** [liourej/CodeDroneDIY#1]
Can you share the wiring?
or any board can be to test this directly?

**Comment by liourej** [comment]
The code can be run on any board using ATmega328P (Arduino Uno, Nano).
Wiring:

Arduino pin | Component
PD2 | receiver
PD4 | ESC0
PD5 | ESC1
PD6 | ESC2
PD7 | ESC3
PC0 | potentiometer
PC4 | SDA MPU6050
PC5 | SCL MPU6050
